#!/usr/bin/env python3
"""Fill player club countries in data/teams.json."""

import argparse
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


COUNTRY_ES = {
    "Algeria": "Argelia",
    "Argentina": "Argentina",
    "Australia": "Australia",
    "Austria": "Austria",
    "Belgium": "Bélgica",
    "Brazil": "Brasil",
    "Canada": "Canadá",
    "Chile": "Chile",
    "China": "China",
    "Colombia": "Colombia",
    "Croatia": "Croacia",
    "Cyprus": "Chipre",
    "Czech Republic": "Chequia",
    "Denmark": "Dinamarca",
    "Ecuador": "Ecuador",
    "Egypt": "Egipto",
    "England": "Inglaterra",
    "France": "Francia",
    "Germany": "Alemania",
    "Greece": "Grecia",
    "Iran": "Irán",
    "Israel": "Israel",
    "Italy": "Italia",
    "Japan": "Japón",
    "Mexico": "México",
    "Netherlands": "Países Bajos",
    "Norway": "Noruega",
    "Poland": "Polonia",
    "Portugal": "Portugal",
    "Russia": "Rusia",
    "Saudi Arabia": "Arabia Saudita",
    "Scotland": "Escocia",
    "Serbia": "Serbia",
    "South Africa": "Sudáfrica",
    "Spain": "España",
    "Switzerland": "Suiza",
    "Turkey": "Turquía",
    "United Arab Emirates": "EAU",
    "United States": "EE.UU.",
}


CLUB_COUNTRY_OVERRIDES = {
    "AC Le Havre": "Francia",
    "AC Milan": "Italia",
    "ACF Fiorentina": "Italia",
    "AE Kifisias": "Grecia",
    "AEK Atenas": "Grecia",
    "AEL Limassol": "Chipre",
    "AFC Ajax": "Países Bajos",
    "AGMK Olmaliq": "Uzbekistán",
    "AJ Auxerre": "Francia",
    "APOEL": "Chipre",
    "AS FAR": "Marruecos",
    "AS Mónaco": "Francia",
    "AS Roma": "Italia",
    "Academia Puerto Cabello": "Venezuela",
    "Ajax": "Países Bajos",
    "Al-Ahli": "Arabia Saudita",
    "Al-Ahli Saudi FC": "Arabia Saudita",
    "Al-Ahly": "Egipto",
    "Al-Ahly SC": "Egipto",
    "Al-Ain": "EAU",
    "Al-Ain FC": "EAU",
    "Al-Arabi SC": "Qatar",
    "Al-Bataeh Club": "EAU",
    "Al-Dhafra SCC": "EAU",
    "Al-Duhail SC": "Qatar",
    "Al-Fayha FC": "Arabia Saudita",
    "Al-Gharafa SC": "Qatar",
    "Al-Ittihad Club": "Arabia Saudita",
    "Al-Ittihad Kalba SCC": "EAU",
    "Al-Karma SC": "Irak",
    "Al-Najma": "Arabia Saudita",
    "Al-Najmah FC": "Arabia Saudita",
    "Al-Nasr FC": "EAU",
    "Al-Nassr FC": "Arabia Saudita",
    "Al-Qadisiyah": "Arabia Saudita",
    "Al-Qadisiyah FC": "Arabia Saudita",
    "Al-Rayyan SC": "Qatar",
    "Al-Sadd SC": "Qatar",
    "Al-Shamal SC": "Qatar",
    "Al-Shorta FC": "Irak",
    "Al-Shorta SC": "Irak",
    "Al-Talaba SC": "Irak",
    "Al-Wahda FC": "EAU",
    "Al-Wakrah SC": "Qatar",
    "Al-Zawraa SC": "Irak",
    "Albirex Niigata": "Japón",
    "Arsenal": "Inglaterra",
    "Atalanta": "Italia",
    "Atalanta BC": "Italia",
    "Athletic Club": "España",
    "Atlanta United": "EE.UU.",
    "Atlético Mineiro": "Brasil",
    "Atlético de Madrid": "España",
    "BSC Young Boys": "Suiza",
    "Barcelona": "España",
    "Barcelona FC": "España",
    "Barnsley FC": "Inglaterra",
    "Bayer 04 Leverkusen": "Alemania",
    "Bayern Munich": "Alemania",
    "Beşiktaş": "Turquía",
    "Beşiktaş JK": "Turquía",
    "Boca Juniors": "Argentina",
    "Bologna FC 1909": "Italia",
    "Bournemouth": "Inglaterra",
    "Brighton": "Inglaterra",
    "Burnley FC": "Inglaterra",
    "CA Huracán": "Argentina",
    "CD Castellón": "España",
    "CD Cobresal": "Chile",
    "CD Marathón": "Honduras",
    "CD Plaza Amador": "Panamá",
    "CD Toluca": "México",
    "CD Tondela": "Portugal",
    "CF América": "México",
    "CF Monterrey": "México",
    "CR Flamengo": "Brasil",
    "Celtic FC": "Escocia",
    "Cerro Porteño": "Paraguay",
    "Chelsea": "Inglaterra",
    "Chelsea FC": "Inglaterra",
    "Chicago Fire": "EE.UU.",
    "Chicago Fire FC": "EE.UU.",
    "Chivas Guadalajara": "México",
    "Club Brujas": "Bélgica",
    "Club León": "México",
    "Club Nacional": "Uruguay",
    "Club Tijuana": "México",
    "Colorado Rapids": "EE.UU.",
    "Corinthians": "Brasil",
    "Coventry City": "Inglaterra",
    "Cremonese": "Italia",
    "Cultural Leonesa": "España",
    "Deportivo La Guaira": "Venezuela",
    "Deportivo Saprissa": "Costa Rica",
    "Dibba Al-Fujairah SCC": "EAU",
    "Dinamo Moskva": "Rusia",
    "Dinamo Samarqand": "Uzbekistán",
    "Dynamo Moscú": "Rusia",
    "El Gouna": "Egipto",
    "Espérance Tunis": "Túnez",
    "Esteghlal FC": "Irán",
    "Estudiantes de La Plata": "Argentina",
    "Everton FC": "Inglaterra",
    "FC Baniyas": "EAU",
    "FC Buxoro": "Uzbekistán",
    "FC Copenhague": "Dinamarca",
    "FC Dallas": "EE.UU.",
    "FC Dender EH": "Bélgica",
    "FC Juárez": "México",
    "FC Lorient": "Francia",
    "FC St. Pauli": "Alemania",
    "FC Stade Nyonnais": "Suiza",
    "FC Torino": "Italia",
    "FC Turan-Tovuz": "Azerbaiyán",
    "FC Twente": "Países Bajos",
    "FC Utrecht": "Países Bajos",
    "FCV Dender EH": "Bélgica",
    "FK Rostov": "Rusia",
    "Fenerbahce SK": "Turquía",
    "Fenerbahçe": "Turquía",
    "Feyenoord": "Países Bajos",
    "Fluminense FC": "Brasil",
    "Foolad FC": "Irán",
    "Frosinone Calcio": "Italia",
    "Fulham FC": "Inglaterra",
    "GNK Dinamo Zagreb": "Croacia",
    "Galatasaray": "Turquía",
    "Galatasaray SK": "Turquía",
    "Genk": "Bélgica",
    "Genoa CFC": "Italia",
    "Girona FC": "España",
    "Granada CF": "España",
    "Grazer AK 1902": "Austria",
    "Gremio": "Brasil",
    "HNK Hajduk Split": "Croacia",
    "HNK Rijeka": "Croacia",
    "Hamburgo SV": "Alemania",
    "Hannover 96": "Alemania",
    "Heart of Midlothian FC": "Escocia",
    "Hearts of Oak": "Ghana",
    "Hellas Verona": "Italia",
    "Heracles Almelo": "Países Bajos",
    "Hoffenheim": "Alemania",
    "Hradec Králové": "Chequia",
    "Hull City": "Inglaterra",
    "Independiente": "Argentina",
    "Independiente Rivadavia": "Argentina",
    "Independiente del Valle": "Ecuador",
    "Inter": "Italia",
    "Inter Miami": "EE.UU.",
    "Inter Milan": "Italia",
    "Inter de Milán": "Italia",
    "Internacional": "Brasil",
    "Ironi Kiryat Shmona": "Israel",
    "Istanbul Basaksehir": "Turquía",
    "Istanbul Basaksehir FK": "Turquía",
    "JS Kabylie": "Argelia",
    "Juventus": "Italia",
    "Juventus FC": "Italia",
    "KS Cracovia": "Polonia",
    "KV Mechelen": "Bélgica",
    "Kaizer Chiefs": "Sudáfrica",
    "Kasımpaşa": "Turquía",
    "LAFC": "EE.UU.",
    "LASK Linz": "Austria",
    "LOSC Lille": "Francia",
    "Lanús": "Argentina",
    "Leicester City": "Inglaterra",
    "Liga de Quito": "Ecuador",
    "Liverpool": "Inglaterra",
    "Lokomotiv Moskva": "Rusia",
    "Luton Town": "Inglaterra",
    "Machida Zelvia": "Japón",
    "Malavan Bandar Anzali": "Irán",
    "Mazatlán FC": "México",
    "Melbourne City FC": "Australia",
    "Melbourne Victory": "Australia",
    "Middlesbrough FC": "Inglaterra",
    "Midtjylland": "Dinamarca",
    "Minnesota United": "EE.UU.",
    "Molde FK": "Noruega",
    "Nasaf Qarshi": "Uzbekistán",
    "Nashville SC": "EE.UU.",
    "Navbahor Namangan": "Uzbekistán",
    "Neftchi Fergana": "Uzbekistán",
    "New York City FC": "EE.UU.",
    "Nordsjælland": "Dinamarca",
    "Nordsjælland FC": "Dinamarca",
    "Norwich City": "Inglaterra",
    "OGC Nice": "Francia",
    "Olimpia": "Paraguay",
    "Olympiakos": "Grecia",
    "Olympique Lyonnais": "Francia",
    "Olympique de Lyon": "Francia",
    "Olympique de Marsella": "Francia",
    "Orlando City": "EE.UU.",
    "Orlando City SC": "EE.UU.",
    "Orlando Pirates": "Sudáfrica",
    "PFC Nasaf Qarshi": "Uzbekistán",
    "Pachuca": "México",
    "Pafos FC": "Chipre",
    "Pakhtakor Tashkent": "Uzbekistán",
    "Panathinaikos": "Grecia",
    "Pari Nizhny Novgorod": "Rusia",
    "Paris FC": "Francia",
    "Paris Saint-Germain": "Francia",
    "Parma Calcio 1913": "Italia",
    "Persepolis FC": "Irán",
    "Persib Bandung": "Indonesia",
    "Philadelphia Union": "EE.UU.",
    "Pogon Szczecin": "Polonia",
    "Polokwane City FC": "Sudáfrica",
    "Port FC": "Tailandia",
    "Porto": "Portugal",
    "Portsmouth": "Inglaterra",
    "Pumas UNAM": "México",
    "RB Bragantino": "Brasil",
    "RC Estrasburgo": "Francia",
    "RS Berkane": "Marruecos",
    "RSC Charleroi": "Bélgica",
    "RSC Union Saint-Gilloise": "Bélgica",
    "Racing de Estrasburgo": "Francia",
    "Randers FC": "Dinamarca",
    "Rangers FC": "Escocia",
    "Real Betis": "España",
    "Real Madrid CF": "España",
    "Real Oviedo": "España",
    "Real Oviedo CF": "España",
    "Real Salt Lake City": "EE.UU.",
    "Roma": "Italia",
    "Royal Antwerp": "Bélgica",
    "SC Braga": "Portugal",
    "SC Internacional": "Brasil",
    "SC Sporting": "Portugal",
    "SE Palmeiras": "Brasil",
    "SL Benfica": "Portugal",
    "SSC Napoli": "Italia",
    "Saint-Étienne": "Francia",
    "Samsunspor": "Turquía",
    "San Diego FC": "EE.UU.",
    "San Lorenzo de Almagro": "Argentina",
    "Santos Laguna": "México",
    "Sarpsborg 08 FF": "Noruega",
    "Sepahan FC": "Irán",
    "Shabab Al-Ahli Dubai": "EAU",
    "Siwelele FC": "Sudáfrica",
    "Slavia Praga": "Chequia",
    "Southampton FC": "Inglaterra",
    "Sparta Praga": "Chequia",
    "St. Gallen": "Suiza",
    "St. Patrick’s Athletic": "Irlanda",
    "Stade Rennais": "Francia",
    "Standard Lieja": "Bélgica",
    "Sunderland": "Inglaterra",
    "Sunderland AFC": "Inglaterra",
    "Surkhon Termiz": "Uzbekistán",
    "Swansea City": "Gales",
    "Sydney FC": "Australia",
    "São Paulo": "Brasil",
    "TSG 1899 Hoffenheim": "Alemania",
    "Talleres de Córdoba": "Argentina",
    "Tigres UANL": "México",
    "Toronto FC": "Canadá",
    "Tottenham": "Inglaterra",
    "Tractor FC": "Irán",
    "U. Católica": "Ecuador",
    "U. de Concepción": "Chile",
    "US Sassuolo": "Italia",
    "USM Alger": "Argelia",
    "Vancouver Whitecaps": "Canadá",
    "Venezia": "Italia",
    "Venezia FC": "Italia",
    "Viktoria Plzen": "Chequia",
    "Viktoria Plzeň": "Chequia",
    "Villarreal": "España",
    "Villarreal CF": "España",
    "Watford FC": "Inglaterra",
    "West Ham": "Inglaterra",
    "Wolfsburg": "Alemania",
    "ZED": "Egipto",
    "Zed": "Egipto",
    "Çaykur Rizespor": "Turquía",
}


def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def write_json(path, data):
    Path(path).write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def build_country_by_club(club_elo_data):
    country_by_club = dict(CLUB_COUNTRY_OVERRIDES)
    for row in club_elo_data.get("clubs", []):
        country = COUNTRY_ES.get(row.get("country"), row.get("country"))
        if country:
            country_by_club.setdefault(row["club"], country)
    return country_by_club


def fill_player_countries(teams_data, country_by_club):
    filled = 0
    missing = []
    for team in teams_data.get("teams", []):
        team_code = team.get("id") or team.get("team_code") or "unknown"
        for player in team.get("players", []):
            if player.get("country"):
                continue
            club = player.get("club")
            country = country_by_club.get(club)
            if country:
                player["country"] = country
                filled += 1
            else:
                missing.append(f"{team_code}:{player.get('name')}:{club}")

    if missing:
        raise ValueError(f"Missing club country mappings: {missing}")

    return filled


def main():
    parser = argparse.ArgumentParser(description="Fill missing player club countries")
    parser.add_argument("--teams", default=str(REPO_ROOT / "data" / "teams.json"))
    parser.add_argument("--club-elo", default=str(REPO_ROOT / "data" / "club_elo.json"))
    args = parser.parse_args()

    teams_path = Path(args.teams)
    teams_data = load_json(teams_path)
    club_elo_data = load_json(args.club_elo)
    filled = fill_player_countries(teams_data, build_country_by_club(club_elo_data))
    write_json(teams_path, teams_data)
    print(json.dumps({"filled": filled}, ensure_ascii=False, sort_keys=True))


if __name__ == "__main__":
    main()
